import { atom } from 'recoil';

import defaultImage from './ui/assets/img/defaultImage.jpg';
import winter1 from './ui/assets/img/winter1.jpg';
import winter2 from './ui/assets/img/winter2.jpg';

export const backgroundState = atom({
  key: 'backgroundProperties',
  default: { isPlaying: false, listOfBackgrounds: [defaultImage, winter1, winter2], selectedBackground: 0 }
});

export const fontState = atom({
  key: 'fontOptions',
  default: {
    fontSize: 22,
    fontColor: 'white',
    fontFamily: { value: 'Arial' },
    fontFamilyList: [
      { value: 'Aharoni', label: 'Aharoni' },
      { value: 'Aharoni Bold', label: 'Aharoni Bold' },
      { value: 'Aldhabi', label: 'Aldhabi' },
      { value: 'AlternateGothic2 BT', label: 'AlternateGothic2 BT' },
      { value: 'Andale Mono' },
      { value: 'Andalus' },
      { value: 'AngsanaUPC' },
      { value: 'Aparajita' },
      { value: 'Apple Chancery' },
      { value: 'Arabic Typesetting' },
      { value: 'Arial' },
      { value: 'Arial Black' },
      { value: 'Arial narrow' },
      { value: 'Arial Nova' },
      { value: 'Arial Rounded MT Bold' },
      { value: 'Arnoldboecklin' },
      { value: 'Avanta Garde' },
      { value: 'Baskerville' },
      { value: 'Batang' },
      { value: 'BatangChe' },
      { value: 'Big Caslon' },
      { value: 'Blippo' },
      { value: 'Bodoni MT' },
      { value: 'Book Antiqua' },
      { value: 'Bookman' },
      { value: 'Calibri' },
      { value: 'Calibri Light' },
      { value: 'Calisto MT' },
      { value: 'Cambodian' },
      { value: 'Cambria' },
      { value: 'Century Gothic' },
      { value: 'Chalkduster' },
      { value: 'Cherokee' },
      { value: 'Comic Sans' },
      { value: 'Comic Sans MS' },
      { value: 'Consolas' },
      { value: 'Constantia' },
      { value: 'Copperplate' },
      { value: 'Copperplate Gothic Light' },
      { value: 'Copperplate Gothic Bold' },
      { value: 'Corbel' },
      { value: 'Cordia New' },
      { value: 'CordiaUPC' },
      { value: 'Coronetscript' },
      { value: 'Courier' },
      { value: 'Courier New' },
      { value: 'Florence' },
      { value: 'Garamond' },
      { value: 'Gautami' },
      { value: 'Geneva' },
      { value: 'Georgia' },
      { value: 'Georgia Pro' },
      { value: 'Impact' },
      { value: 'Levenim MT' },
      { value: 'LilyUPC' },
      { value: 'Lucida Bright' },
      { value: 'Lucida Console' },
      { value: 'Lucida Handwriting' },
      { value: 'Lucida Sans' },
      { value: 'Lucida Sans Typewriter' },
      { value: 'Lucida Sans Unicode' },
      { value: 'Lucidatypewriter' },
      { value: 'Luminari' },
      { value: 'Malgun Gothic' },
      { value: 'Malgun Gothic Semilight' },
      { value: 'Mangal' },
      { value: 'Marker Felt' },
      { value: 'Marlett' },
      { value: 'Meiryo' },
      { value: 'Meiryo UI' },
      { value: 'Microsoft Himalaya' },
      { value: 'Microsoft JhengHei' },
      { value: 'Microsoft JhengHei UI' },
      { value: 'Microsoft New Tai Lue' },
      { value: 'Microsoft PhagsPa' },
      { value: 'Microsoft Sans Serif' },
      { value: 'Microsoft Tai Le' },
      { value: 'Microsoft Uighur' },
      { value: 'Microsoft YaHei' },
      { value: 'Microsoft YaHei UI' },
      { value: 'Microsoft Yi Baiti' },
      { value: 'New Century Schoolbook' },
      { value: 'News Gothic MT' },
      { value: 'Noto' },
      { value: 'Oldtown' },
      { value: 'Optima' },
      { value: 'Palatino' },
      { value: 'Palatino Linotype' },
      { value: 'papyrus' },
      { value: 'Segoe UI' },
      { value: 'Sylfaen' },
      { value: 'Tahoma' },
      { value: 'Thai' },
      { value: 'Times New Roman' },
      { value: 'Vani' },
      { value: 'Verdana' },
      { value: 'Verdana Pro' }
    ]
  }
});
